### ISSUE TITLE
Failed to connect to https://changelogs.ubuntu.com/meta-release

### ISSUE THREAD

**Issue by omerfarukdogan** [GalliumOS/update-manager#2]
MetaReleaseCore raises an exception:

```
>>> from UpdateManager.Core.MetaRelease import MetaReleaseCore
>>> MetaReleaseCore()
MetaRelease.__init__() useDevel=False useProposed=False
/etc/update-manager/meta-release: https://changelogs.ubuntu.com/meta-release 
/etc/update-manager/meta-release: https://changelogs.ubuntu.com/meta-release-lts 
/etc/update-manager/meta-release: -development 
/etc/update-manager/meta-release: -proposed 
metarelease-uri: https://changelogs.ubuntu.com/meta-release
MetaRelease.download()
<UpdateManager.Core.MetaRelease.MetaReleaseCore object at 0x7f0b2095bd68>
>>> result of meta-release download: '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>'
Failed to connect to https://changelogs.ubuntu.com/meta-release. Check your Internet connection or proxy settings
NO self.metarelease_information
```

I can't upgrade my Ubuntu system because of this. I can connect to this address using Chrome, or in Python using `requests`, but `urllib` fails.

```
>>> requests.get("https://changelogs.ubuntu.com/meta-release")
<Response [200]>
```

```
>>> urllib.request.urlopen("https://changelogs.ubuntu.com/meta-release").read()
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
```

**Comment by reynhout** [comment]
I haven't been able to repro this issue on GalliumOS 2.1 or GalliumOS 3.0.

Which version are you running, and how are you trying to update the system? (Recommended method is `galliumos-update` from the command line, or "GalliumOS Update" from the launcher menu)

**Comment by omerfarukdogan** [comment]
@reynhout I'm trying to update with `do-release-upgrade` on Ubuntu 18.04, Python 3.6

**Comment by reynhout** [comment]
@omerfarukdogan

OK, that explains it, then. :)

This GitHub repo is for GalliumOS, which is derived from Ubuntu, but is different enough that the issue you're having isn't something we can fix (or comment authoritatively on).

But to take a quick guess:

Ubuntu 18.04 is the newest Ubuntu still, so `do-release-upgrade` won't have any newer release to upgrade to. Also I'm not sure if LTS releases will "upgrade" to non-LTS releases (it would be a bad idea in many cases!)

Ubuntu has their own support fora, including a Stack Exchange site (AskUbuntu). You'll find someone more knowledgeable there.

Good luck!

**Comment by omerfarukdogan** [comment]
@reynhout Thank you for taking your time to help. I had examined `do-release-upgrade` script and found that it uses `UpdateManager.Core.MetaRelease`. When I Google'd it, only this repository showed up, so I thought it was using this. 18.10 was released a few days ago though, and I have found this issue on askubuntu (no answers yet). Have a good day.
